spring.application.name=api-dominio

# Server Port (Sua API Spring Boot)
server.port=8080

# Conexão com o PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/dominio_lubrificantes
spring.datasource.username=postgres
spring.datasource.password=929248

# 🟢 Configurações do WhatsApp API (Ajustado para a porta da API do WhatsApp, ex: 8085 ou 8081)
whatsapp.api.url=http://localhost:8081
whatsapp.api.key=929248
whatsapp.api.instance=dominio
# WhatsApp que receberá alertas do sistema (estoque baixo, etc.)
oficina.whatsapp.gerente=5524992147851

# Configurações do Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Habilita o agendador de tarefas (@Scheduled)
spring.task.scheduling.pool.size=2